[IDEA] Use glib-compile-resources instead of gdk-pixbuf-csource
GTK4で廃止される`Gdk::Pixbuf::create_from_lnline()`を
`Gdk::Pixbuf::create_from_resource()`で置き換えます。

GResource の参考文献
https://developer.gnome.org/gio/stable/GResource.html
https://developer.gnome.org/gio/stable/glib-compile-resources.html
https://mesonbuild.com/Gnome-module.html
https://stackoverflow.com/questions/1202494/why-doesnt-attribute-constructor-work-in-a-static-library

非推奨のシンボルを無効化するマクロ
```
GDK_DISABLE_DEPRECATED
GTK_DISABLE_DEPRECATED
GDKMM_DISABLE_DEPRECATED
GTKMM_DISABLE_DEPRECATED
GIOMM_DISABLE_DEPRECATED
GLIBMM_DISABLE_DEPRECATED
```

コンパイラのレポート
```
../src/icons/iconmanager.cpp:98:48: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
   98 |     m_list_icons[ ICON::JD16 ] =  Gdk::Pixbuf::create_from_inline( sizeof( icon_jd16 ), icon_jd16 );
      |                                                ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:99:47: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
   99 |     m_list_icons[ ICON::JD32 ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_jd32 ), icon_jd32 );
      |                                               ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:100:47: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  100 |     m_list_icons[ ICON::JD48 ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_jd48 ), icon_jd48 );
      |                                               ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:101:47: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  101 |     m_list_icons[ ICON::JD96 ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_jd96 ), icon_jd96 );
      |                                               ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:104:46: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  104 |     m_list_icons[ ICON::DIR ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_dir ), icon_dir );
      |                                              ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:105:48: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  105 |     m_list_icons[ ICON::IMAGE ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_image ), icon_image );
      |                                                ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:106:47: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  106 |     m_list_icons[ ICON::LINK ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_link ), icon_link );
      |                                               ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:109:48: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  109 |     m_list_icons[ ICON::BOARD ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_board ), icon_board );
      |                                                ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:110:55: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  110 |     m_list_icons[ ICON::BOARD_UPDATE ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_board_update ), icon_board_update );
      |                                                       ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:111:49: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  111 |     m_list_icons[ ICON::THREAD ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_thread ), icon_thread );
      |                                                 ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:112:56: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  112 |     m_list_icons[ ICON::THREAD_UPDATE ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_thread_update ), icon_thread_update );
      |                                                        ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:113:53: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  113 |     m_list_icons[ ICON::THREAD_OLD ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_thread_old ), icon_thread_old );
      |                                                     ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:116:56: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  116 |     m_list_icons[ ICON::BOARD_UPDATED ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_board_updated ), icon_board_updated );
      |                                                        ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:117:57: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  117 |     m_list_icons[ ICON::THREAD_UPDATED ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_thread_updated ), icon_thread_updated );
      |                                                         ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:118:50: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  118 |     m_list_icons[ ICON::LOADING ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_loading ), icon_loading );
      |                                                  ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:119:55: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  119 |     m_list_icons[ ICON::LOADING_STOP ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_loading_stop ), icon_loading_stop );
      |                                                       ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:122:56: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  122 |     m_list_icons[ ICON::BKMARK_UPDATE ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_bkmark_update ), icon_bkmark_update );
      |                                                        ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:123:64: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  123 |     m_list_icons[ ICON::BKMARK_BROKEN_SUBJECT ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_bkmark_broken_subject ), icon_bkmark_broken_subject );
      |                                                                ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:124:49: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  124 |     m_list_icons[ ICON::BKMARK ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_bkmark ), icon_bkmark );
      |                                                 ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:125:49: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  125 |     m_list_icons[ ICON::UPDATE ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_update ), icon_update );
      |                                                 ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:126:52: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  126 |     m_list_icons[ ICON::NEWTHREAD ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_newthread ), icon_newthread );
      |                                                    ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:127:57: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  127 |     m_list_icons[ ICON::NEWTHREAD_HOUR ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_newthread_hour ), icon_newthread_hour );
      |                                                         ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:128:57: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  128 |     m_list_icons[ ICON::BROKEN_SUBJECT ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_broken_subject ), icon_broken_subject );
      |                                                         ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:129:48: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  129 |     m_list_icons[ ICON::CHECK ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_check ), icon_check );
      |                                                ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:130:46: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  130 |     m_list_icons[ ICON::OLD ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_down ), icon_down );
      |                                              ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:131:47: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  131 |     m_list_icons[ ICON::INFO ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_info ), icon_info );
      |                                               ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:134:56: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  134 |     m_list_icons[ ICON::BKMARK_THREAD ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_bkmark_thread ), icon_bkmark_thread );
      |                                                        ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:135:47: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  135 |     m_list_icons[ ICON::POST ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_post ), icon_post );
      |                                               ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:136:53: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  136 |     m_list_icons[ ICON::POST_REFER ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_post_refer ), icon_post_refer );
      |                                                     ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:152:48: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  152 |     m_list_icons[ ICON::WRITE ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_write ), icon_write );
      |                                                ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:163:55: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  163 |     m_list_icons[ ICON::FAVORITEVIEW ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_favorite ), icon_favorite );
      |                                                       ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:164:51: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  164 |     m_list_icons[ ICON::HISTVIEW ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_hist ), icon_hist );
      |                                                   ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:165:57: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  165 |     m_list_icons[ ICON::HIST_BOARDVIEW ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_hist_board ), icon_hist_board );
      |                                                         ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:166:57: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  166 |     m_list_icons[ ICON::HIST_CLOSEVIEW ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_hist_close ), icon_hist_close );
      |                                                         ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:167:62: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  167 |     m_list_icons[ ICON::HIST_CLOSEBOARDVIEW ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_hist_closeboard ), icon_hist_closeboard );
      |                                                              ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:168:60: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  168 |     m_list_icons[ ICON::HIST_CLOSEIMGVIEW ] = Gdk::Pixbuf::create_from_inline( sizeof( icon_hist_closeimg ), icon_hist_closeimg );
      |                                                            ^~~~~~~~~~~~~~~~~~
../src/icons/iconmanager.cpp:178:66: error: 'create_from_inline' is not a member of 'Gdk::Pixbuf'
  178 |     m_list_icons[ ICON::CHECK_UPDATE_OPEN_ROOT ]  = Gdk::Pixbuf::create_from_inline( sizeof( icon_thread ), icon_thread );
      |                                                                  ^~~~~~~~~~~~~~~~~~
```