set ruby-version 3.0
```
Because nokogiri = 1.18.0.rc1 depends on Ruby >= 3.1.0
  and nokogiri >= 1.18.0.rc1, < 1.18.0 depends on RubyGems >= 3.3.22,
  nokogiri >= 1.18.0.rc1, < 1.18.0 requires Ruby >= 3.1.0 or RubyGems >= 3.3.22.
So, because nokogiri = 1.16.2 depends on Ruby >= 3.0.0
  and nokogiri >= 1.16.2, < 1.16.3 depends on Ruby >= 3.0, < 3.4.dev,
nokogiri >= 1.16.2, < 1.16.3 OR >= 1.18.0.rc1, < 1.18.0 requires Ruby >= 3.0.0
or RubyGems >= 3.3.22.
Error: The process '/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle' failed with exit code 6
```