fixup! [TEST] Use std::to_chars() instead of std::to_string()
ubuntu 20.04 gcc 9

error log
```
../src/jdlib/jdiconv.cpp: In member function ‘const char* JDLIB::Iconv::convert(char*, int, int&)’:
../src/jdlib/jdiconv.cpp:198:93: error: no matching function for call to ‘to_chars(char [16], char*, const char32_t&, int)’
  198 |                         const auto result = std::to_chars( uni_str, uni_str + 15, unich, 10 );
      |                                                                                             ^
```