[IDEA] NodeTreeBase: Use indices instead of pointers to access elements
`std::string_view`からポインターを取得する箇所で
スコープ外のローカル変数を示すポインターを使用していると
指摘されたためインデックスでアクセスするようにコードを書き換えます。
(おそらくfalse positive)

cppcheck 2.10のレポート
```
src/dbtree/nodetreebase.cpp:2083:31: error: Using object that points
to local variable 'str_mail' that is out of scope. [invalidLifetime]

(snip)
```

---

codecheck time
```
real    0m13.466s
user    1m23.655s
sys     0m1.318s
```

memory usage and start time
```
pu efb9c24f525 [IDEA] NodeTreeBase: Modify parsing HTML to unconditionally parse <a> elements
in e6256f713b4 [IDEA] NodeTreeBase: Use indices instead of pointers to access elements
ch ea7dde4099f [IDEA] NodeTreeBase: Add bound checks to prevent accessing out of the range
idea1 use const std::string& param for parse_html()

open1
pu bd | 187,584K(1.717s), 187,124K(1.718s), 187,372K(1.654s)
pu asan | 802,512K(5.979s), 816,300K(6.055s), 813,840K(6.035s)
in bd | 178,848K(1.755s), 187,772K(1.799s), 189,636K(1.759s)
in asan | 768,120K(6.278s), 757,884K(6.257s), 777,180K(6.348s)
ch bd | 187,764K(1.950s), 187,960K(1.954s), 188,408K(1.971s)
ch asan | 801,004K(7.261s), 795,896K(7.299s), 796,576K(7.297s)

tab_100
pu bd | 593,280K(2.770s), 593,028K(2.838s), 593,212K(2.805s)
pu asan | 1,212,944K(11.952s), 1,168,208K(11.549s), 1,213,024K(11.716s)
in bd | 593,308K(3.055s), 593,048K(3.092s), 593,164K(3.092s)
in asan | 1,213,004K(12.391s), 1,213,140K(12.083s), 1,214,160K(12.240s)
ch bd | 593,152K(3.300s), 593,008K(3.446s), 593,136K(3.375s)
ch asan | 1,157,104K(20.821s), 1,162,528K(14.206s), 1,162,692K(14.028s), 1,162,668K(13.975s)

largethread
pu bd | 611,172K(4.149s), 611,092K(4.199s), 610,772K(4.246s)
pu asan | 2,278,468K(22.941s), 2,308,292K(23.048s), 2,302,960K(23.189)
in bd | 611,920K(4.650s), 612,056K(4.741s), 612,156K(4.702s)
in asan | 2.278,156K(24.204s), 2,278,460K(23.904s), 2,279,788K(24.062s)
ch bd | 611,812K(5.185s), 612,268K(5.318s), 611,400K(5.300s), 612,004K(5.171s)
ch asan | 2,279,916K(27.933s), 2,284,140K(27.804s), 2,278,892K(27.386s), 2,277,776K(28.386s)
```

bd test: ok
asan test: ok
cppcheck: ok
scan-build: ok